In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
array = np.random.randint(1, high=50, size=10, dtype=int)
media = array.mean()
desvpad = array.std()

print(array)
print(media)
print(desvpad)

[ 8 49 18 47 31 47 15  6 28  9]
25.8
16.240689640529432


[0.98360035 0.21295632 0.03386013 0.43837286 0.70117271 0.40174705
 0.68579313 0.95816365 0.39132823 0.52305316]


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)
print(array)
array[array<=0.5] = np.sqrt(array[array<=0.5])

print("raiz")
print(array)

[0.04886229 0.6158871  0.27227097 0.73664278 0.06456151 0.23388161
 0.10679681 0.37695474 0.88371732 0.98666074]
raiz
[0.22104816 0.6158871  0.52179591 0.73664278 0.25408957 0.48361308
 0.32679782 0.6139664  0.88371732 0.98666074]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3,3,3)

print(matriz)

np.amax(matriz, axis=1)

[[[0.56378393 0.05942564 0.02471777]
  [0.19816759 0.28154461 0.69983641]
  [0.16302303 0.89733747 0.63811001]]

 [[0.32270001 0.10606681 0.029545  ]
  [0.97730806 0.07763175 0.9704784 ]
  [0.54136257 0.6312709  0.61462743]]

 [[0.92607777 0.98626742 0.46127986]
  [0.08818069 0.54957971 0.41761215]
  [0.00695319 0.11141334 0.52281028]]]
Out[37]: array([[0.56378393, 0.89733747, 0.69983641],
       [0.97730806, 0.6312709 , 0.9704784 ],
       [0.92607777, 0.98626742, 0.52281028]])

### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)

def res(x):
  media = (x[0] + x[1] + x[2] + x[3] + x[4])/5
  return [media]

medias = np.apply_along_axis(res, axis=1, arr=matriz)
print("original")
print(matriz)
print("medias")
print(medias)
print("subtracao")
print(matriz-medias)

original
[[0.16669491 0.30333466 0.95583104 0.82740772 0.17061978]
 [0.21060903 0.15492078 0.18305554 0.8457235  0.24923094]
 [0.49359852 0.99579803 0.89315408 0.60019399 0.47452553]
 [0.79851016 0.32309071 0.35700162 0.45903701 0.56875181]
 [0.89693696 0.62506884 0.94501813 0.1347847  0.37813072]]
medias
[[0.48477762]
 [0.32870796]
 [0.69145403]
 [0.50127826]
 [0.59598787]]
subtracao
[[-0.31808271 -0.18144296  0.47105342  0.3426301  -0.31415784]
 [-0.11809893 -0.17378718 -0.14565242  0.51701554 -0.07947702]
 [-0.19785551  0.304344    0.20170005 -0.09126004 -0.2169285 ]
 [ 0.2972319  -0.17818755 -0.14427664 -0.04224126  0.06747355]
 [ 0.30094909  0.02908097  0.34903026 -0.46120317 -0.21785715]]


In [0]:
matriz = np.random.rand(5,5)

media = np.mean(matriz, axis=1)

print(matriz - media[:,np.newaxis])

[[ 0.31564299 -0.10907121 -0.17611673 -0.01958427 -0.01087078]
 [-0.26205881 -0.29005616 -0.02610113  0.05884516  0.51937094]
 [ 0.2040869   0.27142344 -0.17698893 -0.12845196 -0.17006946]
 [ 0.00477627 -0.5471888   0.30089836  0.31998917 -0.07847499]
 [ 0.23211558 -0.25180854  0.45901583 -0.17975673 -0.25956614]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)
print("matriz original")
print(matriz)
print("\n medias")
print("\t juntas")
print(np.mean([matriz.diagonal(),np.diagonal(np.fliplr(matriz))]))
print('\t maior')
print(np.mean(matriz.diagonal()))
print('\t menor')
print(np.mean(np.diagonal(np.fliplr(matriz))))
print("\n desvios")
print("\t juntas")
print(np.std([matriz.diagonal(),np.diagonal(np.fliplr(matriz))]))
print('\t maior')
print(np.std(matriz.diagonal()))
print('\t menor')
print(np.std(np.diagonal(np.fliplr(matriz))))

matriz original
[[3.73024762e-01 6.38194367e-01 3.02582484e-01 8.18236509e-01]
 [3.59780078e-01 8.04221875e-01 1.93402911e-01 5.00561597e-01]
 [8.71819804e-01 6.00056675e-01 7.95697790e-01 6.18356981e-01]
 [8.33927099e-04 7.86896976e-01 3.40018511e-01 5.85045616e-02]]

 medias
	 juntas
0.455497376216241
	 maior
0.5078622470986582
	 menor
0.4031325053338237

 desvios
	 juntas
0.32203252054794795
	 maior
0.3125627160090401
	 menor
0.3228471429901722
